SITE_SUBTITLE: Helping Developers Teach, Lead, Work, and Be More Productive!
SITE_TITLE: Productivity in Tech
SITE_URL: https://productivityintech.com
AUTHOR:
  NAME: Jay Miller
  EMAIL: jay@productivityintech.com
  URL: https://kjaymiller.com
REGION: US/Pacific

